version: '3.7'

services:
  api:
    build: .  # Aqui ele irá procurar pelo Dockerfile no diretório atual
    ports:
      - "3000:3000" 
    environment:  
      - DB_HOST=db
      - DYNAMODB_ENDPOINT=http://db:4566
      - EC2_ENDPOINT=http://db:4566
      - NODE_ENV=development
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
    volumes:
      - .:/src
    networks:
      - app_network
    command: ["npm", "run", "dev",]
    
  db:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" 
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/var/lib/localstack
      - PERSISTENCE=1
      - SERVICES=dynamodb,ec2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Para usar o Docker dentro do contêiner
      - "./localstack_data:/var/lib/localstack"   # Persistindo os dados localmente
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
