FROM node:20-alpine

WORKDIR /app

# Aumentar a memória disponível para o Node.js
ENV NODE_OPTIONS="--max-old-space-size=1024"

# Copiar e instalar dependências
COPY package*.json ./
RUN npm install --production

# Copiar apenas a pasta dist (compilada localmente)
COPY dist ./dist

# Expor a porta da aplicação
EXPOSE 3000

# Rodar a aplicação
CMD ["node", "dist/server.js"]