FROM node:20-alpine

WORKDIR /app

# Aumentar a memória disponível para o Node.js
ENV NODE_OPTIONS="--max-old-space-size=1024"

# Copiar e instalar dependências
COPY package*.json ./
RUN npm install --production

RUN npm run build

COPY dist ./dist

EXPOSE 3000

CMD ["node", "dist/src/server.js"]