
@url_lambd = https://1t6fkph8b7.execute-api.us-east-2.amazonaws.com/prod/create-order
@urlAWS = http://18.223.180.26:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExZjIzMjkxLWZiYmItNGU1Yy04NTQ4LTA4YTc5MzI5NWMyMCIsImlhdCI6MTc0ODkwMDA1NywiZXhwIjoxNzQ4OTAzNjU3fQ.jjcS4_KNZpdval9NvzVs6WZhU62FEslTVJ6yenH3NBA

###
GET http://localhost:3000

###
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: {{token}}

{
    "items": [
            "f09c7319-1240-4d8f-b6ea-b7af16870665",
            "f09c7319-1240-4d8f-b6ea-b7af16870665"
    ]
}

###
POST {{url_lambd}}
Content-Type: application/json
Authorization: {{token}}

{
    "items": [
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e",
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e"
    ]
}

###
DELETE http://localhost:3000/api/orders/d6bd20ed-5fc9-42bb-b486-c152d01e44e4
Authorization: {{token}}
###

GET http://localhost:3000/api/orders/a8a2ec06-b864-4127-a7a3-0f45f02022b5
Authorization: {{token}}

###
GET http://localhost:3000/api/orders
Authorization: {{token}}

###
POST {{urlAWS}}/api/orders
Content-Type: application/json
Authorization: {{token}}

{
    "items": [
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e",
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e"
    ]
}

###
GET {{urlAWS}}/api/orders
Authorization: {{token}}

###
DELETE {{urlAWS}}/api/orders/d6bd20ed-5fc9-42bb-b486-c152d01e44e4
Authorization: {{token}}

###
GET {{urlAWS}}/api/orders/1d342119-3a78-4128-8b66-0b81c26de226
Authorization: {{token}}
