
@url_lambd = https://1t6fkph8b7.execute-api.us-east-2.amazonaws.com/prod/create-order
@urlAWS = http://18.223.180.26:3000


###
GET http://localhost:3000

###
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExZjIzMjkxLWZiYmItNGU1Yy04NTQ4LTA4YTc5MzI5NWMyMCIsImlhdCI6MTc0MTcyNDExMywiZXhwIjoxNzQxNzI3NzEzfQ.Q6CRCUNGqEnkYbJHlHsaZjPAgigl0XCxQBEpB5RKxM4

{
    "items": [
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e",
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e"
    ]
}

###
POST {{url_lambd}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExZjIzMjkxLWZiYmItNGU1Yy04NTQ4LTA4YTc5MzI5NWMyMCIsImlhdCI6MTc0NjY1ODM3MywiZXhwIjoxNzQ2NjYxOTczfQ.G6nXjXMUPSHD6qCeYpDnKNIuwd2EuGDdhJcUXWtnBAo

{
    "items": [
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e",
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e"
    ]
}

###
DELETE http://localhost:3000/api/orders/d6bd20ed-5fc9-42bb-b486-c152d01e44e4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExZjIzMjkxLWZiYmItNGU1Yy04NTQ4LTA4YTc5MzI5NWMyMCIsImlhdCI6MTc0NjM5MDU3NiwiZXhwIjoxNzQ2Mzk0MTc2fQ.W8FWWt-Jmkcp6m6rqkAiccjTjrdeBeTQvs
###

GET http://localhost:3000/api/orders/a8a2ec06-b864-4127-a7a3-0f45f02022b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExZjIzMjkxLWZiYmItNGU1Yy04NTQ4LTA4YTc5MzI5NWMyMCIsImlhdCI6MTc0NjM5MDYzMSwiZXhwIjoxNzQ2Mzk0MjMxfQ.78g4q3d1srIKhMpNN_8pH8BlnMwlGJGuwPv0kZRL07s

###
GET http://localhost:3000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExZjIzMjkxLWZiYmItNGU1Yy04NTQ4LTA4YTc5MzI5NWMyMCIsImlhdCI6MTc0MTcyNDExMywiZXhwIjoxNzQxNzI3NzEzfQ.Q6CRCUNGqEnkYbJHlHsaZjPAgigl0XCxQBEpB5RKxM4

###
POST {{urlAWS}}/api/orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyZGNjOWNhLTBlMzgtNDYwNS1hZmM1LTM0MGRkZTFmNDg0MSIsImlhdCI6MTc0Nzg2MDM3OSwiZXhwIjoxNzQ3ODYzOTc5fQ.Poee6gC3dBGQK3fBsV02zT2s3NETvm48WXz0BmratHA

{
    "items": [
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e",
            "b2dcc9ca-0e38-4605-afc5-340dde1f484e"
    ]
}

###
GET {{urlAWS}}/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyZGNjOWNhLTBlMzgtNDYwNS1hZmM1LTM0MGRkZTFmNDg0MSIsImlhdCI6MTc0Nzg2MDM3OSwiZXhwIjoxNzQ3ODYzOTc5fQ.Poee6gC3dBGQK3fBsV02zT2s3NETvm48WXz0BmratHA

###
DELETE {{urlAWS}}/api/orders/d6bd20ed-5fc9-42bb-b486-c152d01e44e4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyZGNjOWNhLTBlMzgtNDYwNS1hZmM1LTM0MGRkZTFmNDg0MSIsImlhdCI6MTc0Nzg2MDM3OSwiZXhwIjoxNzQ3ODYzOTc5fQ.Poee6gC3dBGQK3fBsV02zT2s3NETvm48WXz0BmratHA

###
GET {{urlAWS}}/api/orders/1d342119-3a78-4128-8b66-0b81c26de226
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyZGNjOWNhLTBlMzgtNDYwNS1hZmM1LTM0MGRkZTFmNDg0MSIsImlhdCI6MTc0Nzg2MDM3OSwiZXhwIjoxNzQ3ODYzOTc5fQ.Poee6gC3dBGQK3fBsV02zT2s3NETvm48WXz0BmratHA
