
@urlAWS = http://18.223.180.26:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1MGM5MmFkLWFkZjQtNGE0My04OTRmLTE1YTY0ZGY2NWY4OCIsImlhdCI6MTc0ODk0NDI3MywiZXhwIjoxNzQ4OTQ3ODczfQ.oVU96KK09f1Fhgh4VHR-_Mk0p7vYOcTI52E7ADDQaI4
###
GET http://localhost:3000

###
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: {{token}}

{
    "name": "celular",
    "price": 303,
    "stock": 50
}

###
DELETE http://localhost:3000/api/products/79c344fe-40de-4863-a794-c5745db2d1b2
Authorization: {{token}}
###

GET http://localhost:3000/api/products/id/f09c7319-1240-4d8f-b6ea-b7af16870665
Authorization: {{token}}

###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/name/Mouse%20Gamer
Authorization: {{token}}

###
POST {{urlAWS}}/api/products
Content-Type: application/json
Authorization: {{token}}

{
    "name": "teclado",
    "price": 303,
    "stock": 50
}

###
GET {{urlAWS}}/api/products
Authorization: {{token}}

###
DELETE {{urlAWS}}/api/products/79c344fe-40de-4863-a794-c5745db2d1b2
Authorization: {{token}}

###
GET {{urlAWS}}/api/products/id/b87e3e2e-2f6c-473a-b5ce-0ceba9e7eff0
Authorization: {{token}}

###
GET {{urlAWS}}/api/products/name/teclado
Authorization: {{token}}

###


