@baseUrl = http://localhost:3000

@urlAWS = http://13.58.230.90:3000

@lambdaUrl = https://1t6fkph8b7.execute-api.us-east-2.amazonaws.com/prod/create-order

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyZGNjOWNhLTBlMzgtNDYwNS1hZmM1LTM0MGRkZTFmNDg0MSIsImlhdCI6MTc0OTA1MDgwOCwiZXhwIjoxNzQ5MDU0NDA4fQ.fFNyk2QaRYXBzxf8PPh_4mzXtcq2I_kUsZummDFRgVM

### 1. Criar order via Lambda (envia para SQS)
POST {{lambdaUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items": [
        "b2dcc9ca-0e38-4605-afc5-340dde1f484e",
        "b2dcc9ca-0e38-4605-afc5-340dde1f484e"
    ]
}

###
GET {{baseUrl}}/api/orders
Authorization: {{token}}

### Processar fila manualmente
POST {{baseUrl}}/api/orders/process-queue
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/orders/worker/status
Authorization: {{token}}
###
POST {{baseUrl}}/api/orders/worker/stop
Authorization: {{token}}
###
POST {{baseUrl}}/api/orders/worker/start
Authorization: {{token}}

###
GET {{urlAWS}}/api/orders
Authorization: {{token}}

###
POST {{urlAWS}}/api/orders/process-queue
Content-Type: application/json
Authorization: {{token}}


### Fluxo de Teste Completo:
# 1. Pare a API (Ctrl+C)
# 2. Criar order via Lambda
# 3. Inicie a API novamente
# 4. Processar fila manualmente ou aguarde o worker automático
# 5. Verificar se os orders foram processados 