###
GET http://localhost:3000

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "video",
    "email": "erik@live.com",
    "password": "11111111"
}

###
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyNWI5NjViLTExZDQtNGQyZS1iYWEzLTg0MzcxZjY5OTAxOCIsImlhdCI6MTc0MTM4MjI4MiwiZXhwIjoxNzQxMzg1ODgyfQ.xMxxu9QVB7o5Sa1SYQbbkU5l1Xjl_7l1Y1ChL7dHUPE
