name: Deploy to ECS

on:
  push:
    branches:
      - desativado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t erikbarroso/order-api:latest -f Dockerfile.production .
        docker push erikbarroso/order-api:latest

    - name: Update ECS Task Definition
      run: |
        aws ecs register-task-definition \
        --family task-order-api \
        --container-definitions '[{
            "name": "container-order-api",
            "image": "erikbarroso/order-api:latest",
            "memory": 350,
            "cpu": 350,
            "essential": true,
            "portMappings": [{
            "containerPort": 3000,
            "hostPort": 3000
            }]
        }]' \
        --region us-east-2

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
        --cluster order-api \
        --service service-order-api \
        --task-definition task-order-api \
        --force-new-deployment \
        --region us-east-2

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster order-api --service service-order-api --force-new-deployment --region us-east-2